title: International Press journal AMSA author support
description: TeX related material for the manuscript preparation for the 
             International Press journal Annals of Mathematical Sciences and Applications
             (AMSA)
show_downloads: true
theme: jekyll-theme-tactile
